### ISSUE TITLE
Essential bug

### ISSUE THREAD

**Issue by Juno-zip** [RecraftorsMC/blahaj#14]
Item cannot craft or be given to the player while in an Essential multiplayer server?

**Comment by NerjalNosk** [comment]
Please provide more information as for:
* Played game version
* Used mod version
* Whether all players do have the mod
* The host's game log (and possibly server log, if Essential does split logs between regular client and its custom host system)
* The player who attempted to run the command's log

**Comment by Juno-zip** [comment]
both current version, of game, essential, and blahaj mod
all players have the mod installed
i cannot get the hosts log at this time, i will update you when i can

**Comment by NerjalNosk** [comment]
Wdym "current version"? Just give the actual game version (e.g. 1.20.1, 1.29.2, etc), as well as the mods (both Essential andBlahaj) versions (should be shown using ModMenu or in your launcher).

Just saying "it doesn't work" doesn't tell me anything about what is actually happening and doesn't let me figure out what is the real cause of the issue.

**Comment by Juno-zip** [comment]
1.20.1. the only version this mod is compatible with.

**Comment by NerjalNosk** [comment]
No? There are releases for 1.19 all the way to 1.20.4

**Comment by Juno-zip** [comment]
i misread the desc. my bad
thats for melodies

**Comment by NerjalNosk** [comment]
Immersive Melodies integration still exists for both 1.19 and 1.20, but anyway. I cannot help you without more insight, by the means of logs

**Comment by NerjalNosk** [comment]
As you are no longer providing any input, I will consider that you figured out the actual cause of your problem, and will then be closing the issue. Feel free to open it again with more input if you have anything to add.
