### ISSUE TITLE
Crash when clicking "Create New World"

### ISSUE THREAD

**Issue by LeeSpork** [RecraftorsMC/blahaj#4]
Minecraft 1.20.2 with Fabric Loader 0.15.3
mods: `blahaj_1.20-0.5.1.jar` and `fabric-api-0.91.2+1.20.2.jar`

**Comment by LeeSpork** [comment]
Also happens with blahaj 0.5.0 and 0.4.0; Version 0.2.0 doesn't have this crash.

**Comment by NerjalNosk** [comment]
It would be appreciated to have some form of logs, crash logs and alike, to be able to trace back the actual source of the issue

**Comment by LeeSpork** [comment]
[latest.log](https://github.com/RecraftorsMC/blahaj/files/13802653/latest.log)
[crash-2024-01-01_16.29.41-client.txt](https://github.com/RecraftorsMC/blahaj/files/13802655/crash-2024-01-01_16.29.41-client.txt)

**Comment by NerjalNosk** [comment]
Same bug as #5, fixed in 0.5.1+1.20.2
