### ISSUE TITLE
Windows thinks 0.6.1 version is a wacatac trojan

### ISSUE THREAD

**Issue by LeeSpork** [RecraftorsMC/blahaj#9]
This is quite possibly more Microsoft's fault than your fault, but I get a Windows Defender notification when I download version 0.6.1 for 1.20.1 from Modrinth.

This doesn't happen with the 0.6.0 jar that I downloaded last week.

![image](https://github.com/RecraftorsMC/blahaj/assets/24984194/8e9c9ea0-d32f-4df7-9478-d32eb3a7895b)

**Comment by NerjalNosk** [comment]
I must admit, I was rather surprised when I read this.

While I would have highly doubted it, I couldn't rule out the fact that maybe a suspicious program infected my own device and would have actually also modified the mod jar out of my knowledge before I could publish it. Even if the Modrinth security systems tend to be rather on-mark with potential malware in disguise.

Hence, I decided to decompile the very build file that I published, and check for any code that wouldn't match the one that I made myself. And as I expected, there was nothing that went beyond my own code.

Thus, I would guess that this message is either a false positive malware detection (so Windows indeed being dumb), or another malware that would already be on your device that modified the file as you had just downloaded it.

Thank you for sharing it it with us though
